name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Provided by GitHub
        publish_dir: ./  # Deploy the root directory
